version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-04-01 to 2022-03-15 by week"
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv

  generate_oximetry_timeseries:
    run: python:latest python analysis/analysis1.py
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        table_1_oximetry_counts: output/table_1_oximetry_counts.csv
        plot_1_oximetry_timeseries: output/plot_1_oximetry_timeseries.png

  generate_age_timeseries:
    run: python:latest python analysis/analysis2.py
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        table_2_age_counts: output/table_2_age_counts.csv
        plot_2_age_timeseries: output/plot_2_age_timeseries.png