version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2021-11-01 to 2021-12-28 by week"
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv

  generate_oximetry_timeseries:
    run: python:latest python analysis/analysis1.py
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        table_1_oximetry_counts: output/table_1_oximetry_counts.csv
        plot_1_oximetry_timeseries: output/plot_1_oximetry_timeseries.png

  generate_oximetry_regional_timeseries:
    run: python:latest python analysis/analysis_region.py
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        table_oximetry_counts_region: output/table_oximetry_counts_*.csv
        plot_oximetry_timeseries_region: output/plot_oximetry_timeseries_region_*.png

  generate_timeseries_breakdowns:
    run: python:latest python analysis/analysis2.py
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        table_1325191000000108_counts: output/table_1325191000000108_*.csv
        plot_1325191000000108_timeseries: output/plot_1325191000000108_*.png
        table_1325221000000101_counts: output/table_1325221000000101_*.csv
        plot_1325221000000101_timeseries: output/plot_1325221000000101_*.png
        table_1325241000000108_counts: output/table_1325241000000108_*.csv
        plot_1325241000000108_timeseries: output/plot_1325241000000108_*.png