version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-04-01 to 2022-03-15 by week"
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv

  generate_oximetry_timeseries:
    run: python:latest python analysis/analysis1.py
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        table_1_oximetry_counts: output/table_1_oximetry_counts.csv
        plot_1_oximetry_timeseries: output/plot_1_oximetry_timeseries.png

  generate_timeseries_breakdowns:
    run: python:latest python analysis/analysis2.py
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        table_1325191000000108_age_group_counts: output/tables/table_1325191000000108_age_group_counts.csv
        plot_1325191000000108_age_group_timeseries: output/timeseries/plot_1325191000000108_age_group_timeseries.png
        table_1325221000000101_age_group_counts: output/tables/table_1325221000000101_age_group_counts.csv
        plot_1325221000000101_age_group_timeseries: output/timeseries/plot_1325221000000101_age_group_timeseries.png
        table_1325241000000108_age_group_counts: output/tables/table_1325241000000108_age_group_counts.csv
        plot_1325241000000108_age_group_timeseries: output/timeseries/plot_1325241000000108_age_group_timeseries.png
        table_1325191000000108_shielding_counts: output/tables/table_1325191000000108_shielding_counts.csv
        plot_1325191000000108_shielding_timeseries: output/timeseries/plot_1325191000000108_shielding_timeseries.png
        table_1325221000000101_shielding_counts: output/tables/table_1325221000000101_shielding_counts.csv
        plot_1325221000000101_shielding_timeseries: output/timeseries/plot_1325221000000101_shielding_timeseries.png
        table_1325241000000108_shielding_counts: output/tables/table_1325241000000108_shielding_counts.csv
        plot_1325241000000108_shielding_timeseries: output/timeseries/plot_1325241000000108_shielding_timeseries.png
        table_1325191000000108_sex_counts: output/tables/table_1325191000000108_sex_counts.csv
        plot_1325191000000108_sex_timeseries: output/timeseries/plot_1325191000000108_sex_timeseries.png
        table_1325221000000101_sex_counts: output/tables/table_1325221000000101_sex_counts.csv
        plot_1325221000000101_sex_timeseries: output/timeseries/plot_1325221000000101_sex_timeseries.png
        table_1325241000000108_sex_counts: output/tables/table_1325241000000108_sex_counts.csv
        plot_1325241000000108_sex_timeseries: output/timeseries/plot_1325241000000108_sex_timeseries.png
        table_1325191000000108_care_home_counts: output/tables/table_1325191000000108_care_home_counts.csv
        plot_1325191000000108_care_home_timeseries: output/timeseries/plot_1325191000000108_care_home_timeseries.png
        table_1325221000000101_care_home_counts: output/tables/table_1325221000000101_care_home_counts.csv
        plot_1325221000000101_care_home_timeseries: output/timeseries/plot_1325221000000101_care_home_timeseries.png
        table_1325241000000108_care_home_counts: output/tables/table_1325241000000108_care_home_counts.csv
        plot_1325241000000108_care_home_timeseries: output/timeseries/plot_1325241000000108_care_home_timeseries.png
        table_1325191000000108_ethnicity_6_sus_counts: output/tables/table_1325191000000108_ethnicity_6_sus_counts.csv
        plot_1325191000000108_ethnicity_6_sus_timeseries: output/timeseries/plot_1325191000000108_ethnicity_6_sus_timeseries.png
        table_1325221000000101_ethnicity_6_sus_counts: output/tables/table_1325221000000101_ethnicity_6_sus_counts.csv
        plot_1325221000000101_ethnicity_6_sus_timeseries: output/timeseries/plot_1325221000000101_ethnicity_6_sus_timeseries.png
        table_1325241000000108_ethnicity_6_sus_counts: output/tables/table_1325241000000108_ethnicity_6_sus_counts.csv
        plot_1325241000000108_ethnicity_6_sus_timeseries: output/timeseries/plot_1325241000000108_ethnicity_6_sus_timeseries.png
        table_1325191000000108_IMD_decile_counts: output/tables/table_1325191000000108_IMD_decile_counts.csv
        plot_1325191000000108_IMD_decile_timeseries: output/timeseries/plot_1325191000000108_IMD_decile_timeseries.png
        table_1325221000000101_IMD_decile_counts: output/tables/table_1325221000000101_IMD_decile_counts.csv
        plot_1325221000000101_IMD_decile_timeseries: output/timeseries/plot_1325221000000101_IMD_decile_timeseries.png
        table_1325241000000108_IMD_decile_counts: output/tables/table_1325241000000108_IMD_decile_counts.csv
        plot_1325241000000108_IMD_decile_timeseries: output/timeseries/plot_1325241000000108_IMD_decile_timeseries.png