version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2021-01-01 to 2021-03-01 by week"
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv
