version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-04-01 to 2022-02-25 by week"
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv

  run_model:
    run: python:latest python analysis/analysis1.py
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        oximetry_sums_table: output/oximetry_sums.csv
        oximetry_timeseries_figure: output/oximetry_timeseries.png